<?php 
	chong_pha_hoai();
?>
<?php 
	//echo $_POST['them_san_pham'];
	//thongbao("dung lai");
	if($_POST['them_san_pham']=="them_san_pham")
	{
		include("cumchucnang/du_lieu/san_pham/thuc_hien_them.php");
		trangtruoc();
		//exit();
	}
	if($_POST['sua_san_pham']=="sua_san_pham")
	{
		include("cumchucnang/du_lieu/san_pham/thuc_hien_sua.php");
		trangtruoc();
		//exit();
	}
	if($_GET['thamso']=="xoa_san_pham")
	{
		include("cumchucnang/du_lieu/san_pham/xoa.php");
		trangtruoc();
		//exit();
	}
	if($_POST['them_tin_tuc']=="them_tin_tuc")
	{
		include("cumchucnang/du_lieu/tin_tuc/thuc_hien_them.php");
		trangtruoc();
		//exit();
	}
	if($_POST['sua_tin_tuc']=="sua_tin_tuc")
	{
		include("cumchucnang/du_lieu/tin_tuc/thuc_hien_sua.php");
		trangtruoc();
		//exit();
	}
	if($_GET['thamso']=="xoa_tin_tuc")
	{
		include("cumchucnang/du_lieu/tin_tuc/xoa.php");
		trangtruoc();
		//exit();
	}
	if($_POST['sua_du_lieu_mot_tin']=="sua_du_lieu_mot_tin")
	{
		include("cumchucnang/du_lieu/du_lieu_mot_tin/thuc_hien_sua.php");
		trangtruoc();
		//exit();
	}
	if($_GET['thamso']=="xoa_hoa_don")
	{
		include("cumchucnang/hoa_don/xoa.php");
		trangtruoc();
		//exit();
	}
	if($_GET['thamso']=="xoa_hoa_don__2")
	{
		include("cumchucnang/hoa_don/xoa_2.php");
		trangtruoc();
		//exit();
	}
	if($_POST['sua_thanh_vien']=="sua_thanh_vien")
	{
		include("cumchucnang/thanh_vien/thuc_hien_sua.php");
		trangtruoc();
		//exit();
	}
	if($_GET['thamso']=="xoa_thanh_vien")
	{
		include("cumchucnang/thanh_vien/xoa.php");
		trangtruoc();
		//exit();
	}
	if($_POST['them_menu_ngang']=="them_menu_ngang")
	{
		include("cumchucnang/menu_ngang/thuc_hien_them.php");
		trangtruoc();
		//exit();
	}
	if($_POST['sua_menu_ngang']=="sua_menu_ngang")
	{
		include("cumchucnang/menu_ngang/thuc_hien_sua.php");
		trangtruoc();
		//exit();
	}
	if($_GET['thamso']=="xoa_menu_ngang")
	{
	}
	if($_POST['them_menu_doc']=="them_menu_doc")
	{
		include("cumchucnang/menu_doc/thuc_hien_them.php");
		trangtruoc();
		//exit();
	}
	if($_POST['sua_menu_doc']=="sua_menu_doc")
	{
		include("cumchucnang/menu_doc/thuc_hien_sua.php");
		trangtruoc();
		//exit();
	}
	if($_GET['thamso']=="xoa_menu_doc")
	{
		include("cumchucnang/menu_doc/xoa.php");
		trangtruoc();
		//exit();
	}
	if($_POST['cap_nhat__sptt']=="cap_nhat__sptt")
	{
		include("cumchucnang/san_pham_trang_chu/cap_nhat__sptt.php");
		trangtruoc();
		//exit();
	}
	if($_POST['them_nick_yahoo']=="them_nick_yahoo")
	{
		include("cumchucnang/ho_tro_truc_tuyen/thuc_hien_them.php");
		trangtruoc();
		//exit();
	}
	if($_POST['sua_nick_yahoo']=="sua_nick_yahoo")
	{
		include("cumchucnang/ho_tro_truc_tuyen/thuc_hien_sua.php");
		trangtruoc();
		//exit();
	}
	if($_GET['thamso']=='xoa_nick_yahoo')
	{
		include("cumchucnang/ho_tro_truc_tuyen/xoa.php");
		trangtruoc();
		//exit();
	}
	if($_POST['them_quang_cao_trai']=="them_quang_cao_trai")
	{
		include("cumchucnang/quang_cao/trai/thuc_hien_them.php");
		trangtruoc();
		//exit();
	}
	if($_POST['sua_quang_cao_trai']=='sua_quang_cao_trai')
	{
		include("cumchucnang/quang_cao/trai/thuc_hien_sua.php");
		trangtruoc();
		//exit();
	}
	if($_GET['thamso']=="xoa_quang_cao_trai")
	{
		include("cumchucnang/quang_cao/trai/xoa.php");
		trangtruoc();
		//exit();
	}
	if($_POST['them_quang_cao_phai']=="them_quang_cao_phai")
	{
		include("cumchucnang/quang_cao/phai/thuc_hien_them.php");
		trangtruoc();
		//exit();
	}
	if($_POST['sua_quang_cao_phai']=='sua_quang_cao_phai')
	{
		include("cumchucnang/quang_cao/phai/thuc_hien_sua.php");
		trangtruoc();
		//exit();
	}
	if($_GET['thamso']=="xoa_quang_cao_phai")
	{
		include("cumchucnang/quang_cao/phai/xoa.php");
		trangtruoc();
		//exit();
	}
	if($_POST['thay_doi_lien_he']=="thay_doi_lien_he")
	{
		include("cumchucnang/thay_doi_lien_he/thuc_hien_thay_doi_lien_he.php");
		trangtruoc();
		//exit();
	}
	if($_POST['thay_doi_banner']=="thay_doi_banner")
	{
		include("cumchucnang/banner/thuc_hien_sua.php");
		trangtruoc();
		//exit();
	}
	if($_POST['thay_doi_footer']=="thay_doi_footer")
	{
		include("cumchucnang/footer/thuc_hien_sua.php");
		trangtruoc();
		//exit();
	}
	if(isset($_POST['thay_doi_thong_tin_quan_tri']))
	{
		if($_POST['thay_doi_thong_tin_quan_tri']=="thay_doi_thong_tin_quan_tri")
		{
			include("cumchucnang/dang_nhap_quan_ly/thuc_hien__thay_doi_thong_tin_quan_tri.php");
		}
		
	}

	
?>